baseURL = "https://hojeediadeque.netlify.app/"
languageCode = "pt-br"
title = "Hoje é dia de quê?"
description = "Descubra o que se comemora hoje no Brasil e no mundo. Veja aniversários, fatos históricos e curiosidades diárias."
author = "Fernando Moura"
theme = "PaperMod"

[params]
defaultTheme = "light"
ShowReadingTime = false
ShowShareButtons = true
ShowPostNavLinks = true

[menu]
[[menu.main]]
name = "Início"
url = "/"
weight = 1

[[menu.main]]
name = "Sobre"
url = "/sobre/"
weight = 2


# SEO
enableRobotsTXT = true
canonifyURLs = true